### ISSUE TITLE
Save config can crash companion

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-generic-mqtt#4]
Not unique to this module, but when the mqtt was 'Offline' I clicked update in the instance config panel to try and force it to reconnect and instead it crashed companion.
It is simply needing a try-catch around this block of code, and probably others to avoid this happening

```
Aug 31 08:37:30 companion-pi node[2148]: TypeError: Cannot read property 'forEach' of undefined
Aug 31 08:37:30 companion-pi node[2148]:     at MqttClient.unsubscribe (/home/ubuntu/companion-build/companion/lib/module/generic-mqtt/node_modules/mqtt/lib/client.js:690:28)
Aug 31 08:37:30 companion-pi node[2148]:     at self.mqtt_topic_subscriptions.forEach (/home/ubuntu/companion-build/companion/lib/module/generic-mqtt/index.js:66:20)
Aug 31 08:37:30 companion-pi node[2148]:     at Map.forEach (<anonymous>)
Aug 31 08:37:30 companion-pi node[2148]:     at instance._resubscribeToTopics (/home/ubuntu/companion-build/companion/lib/module/generic-mqtt/index.js:65:33)
Aug 31 08:37:30 companion-pi node[2148]:     at instance._initMqtt (/home/ubuntu/companion-build/companion/lib/module/generic-mqtt/index.js:361:8)
Aug 31 08:37:30 companion-pi node[2148]:     at instance.updateConfig (/home/ubuntu/companion-build/companion/lib/module/generic-mqtt/index.js:50:8)
Aug 31 08:37:30 companion-pi node[2148]:     at EventEmitter.<anonymous> (/home/ubuntu/companion-build/companion/lib/instance.js:388:21)
Aug 31 08:37:30 companion-pi node[2148]:     at emitTwo (events.js:126:13)
Aug 31 08:37:30 companion-pi node[2148]:     at EventEmitter.emit (events.js:214:7)
Aug 31 08:37:30 companion-pi node[2148]:     at Socket.<anonymous> (/home/ubuntu/companion-build/companion/lib/instance.js:538:15)
```

**Comment by Julusian** [comment]
Thanks, I have rebased and merged the PR for this onto the overhaul for companion 3.0, so expect it to be available once 3.0 hits beta
